.SUFFIXES = .c .o

CC = gcc
CFLAGS = -g

fork_example:
	$(CC) $(CFLAGS) fork_example.c -o fork_example.out

wait_example:
	$(CC) $(CFLAGS) wait_example.c -o wait_example.out

waitpid_example:
	$(CC) $(CFLAGS) waitpid_example.c -o waitpid_example.out

execl_example:
	$(CC) $(CFLAGS) execl_example.c -o execl_example.out

clean:
	rm -f *.out
